### ISSUE TITLE
FA4 to FA6 Shim

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-libraries#4]
There's a lot of icons that seem broken after migration according to the shim.  

One pattern that seems to happen a lot is that icons that end in `-o` (e.g. FA4's fa-lightbulb-o) don't get moved over to the non `-o` version (e.g. FA6's fa-lightbulb).

I haven't looked at the code here but if there's a way to add a regex to this to strip the `-o` from the end of the source icon names that would solve this issue in the main.  

Is this possible or something that we'll have to do in the migration codebase?

**Comment by jnicholCU** [comment]
@jcsparks is this solved now with the new change?

**Comment by jcsparks** [comment]
Adding in the shim fixed the issue... closing now.
